version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1


      # - restore_cache:
      #   key: composer-v2-{{ checksum "ability/composer.lock" }
      - run:
          working_directory: ability
          command: composer install -n --prefer-dist
      # - save_cache:
      #     key: composer-v2-{{ checksum "ability/composer.lock" }}
      #     paths:
      #       - ability/vendor


      - run:
          working_directory: ability
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - run:
          working_directory: ability
          command: npm run dev
      - run:
          working_directory: ability
          name: php test
          command: vendor/bin/phpunit

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/php:7.4-node-browsers
#     steps:
#       - checkout

      # - restore_cache:
      #     key: composer-v2-{{ checksum "laravel/composer.lock" }}
      # - run:
      #     working_directory: laravel
      #     command: composer install -n --prefer-dist
      # - run:
      #     working_directory: laravel
      #     name: npm ci
      #     command: |
      #       if [ ! -d node_modules ]; then
      #         npm ci
      #       fi
      # - save_cache:
      #     key: npm-v2-{{ checksum "laravel/package-lock.json" }}
      #     paths:
      #       - laravel/node_modules
#       - run:
#           working_directory: laravel
#           command: npm run dev
#       - run:
#           working_directory: laravel
#           name: php test
#           command: vendor/bin/phpunit
