version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --working-dir=./ability
      - run: npm ci --prefix=./ability
      - run: npm run dev --prefix=./ability
      - run:
          name: php test
          command: ./ability/vendor/bin/phpunit

          # aa
